connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse:8123/default
connection-user=${ENV:CLICKHOUSE_USER}
connection-password=${ENV:CLICKHOUSE_PASSWORD}
clickhouse.map-string-as-varchar=true